### ISSUE TITLE
Can't generate a node with child nodes of same name

### ISSUE THREAD

**Issue by twang4turner** [michalcarson/SymfonyXmlResponse#1]
Hi,

The library is great and very easy to use. I have a question: we need to generate a xml with a files node that contains a list of 'file' child nodes like the following:

<files>
<file>file1.txt</file>
<file>fle2.txt</file>
<file>file3.txt</file>
</files>

Since we can't duplicate keys in an array, how can I create the "files" node?

Your help would be greatly appreciated!

**Comment by michalcarson** [comment]
Hi, and thanks for the input.

So what we would like to do is

```
['files' => [
    'file' => 'file1.txt',
    'file' => 'file2.txt',
    'file' => 'file3.txt'
    ]
]
```

...but a PHP array can't do that.

I don't have an answer handy. Maybe we could look at the Symfony JSON response to see if this kind of thing has been handled. I'm open to suggestions.

**Comment by twang4turner** [comment]
Hi Michal,

Thank you very much for your quick response! I will take a look. Please share with me if you come up with a solution.

Just let you know that other than that, your library works very well and we really appreciate that.

**Comment by deviantintegral** [comment]
JsonResponse doesn't handle this because you can't have multiple "nodes" with the same name.

Is there anything in <a href="http://symfony.com/doc/2.8/components/serializer.html">symfony/serializer</a> that would help? It looks like we could change this to accept an object and a normalizer for the object in the constructor, and then rely on that to actually generate the XML.

**Comment by deviantintegral** [comment]
And another thought - if we had a response class that accepted any `Symfony\Component\Serializer\Encoder\EncoderInterface`, wouldn't that work for XML, JSON, or any other serializable format? But like the project page says, I'm surprised I'm not finding something for this already.

**Comment by michalcarson** [comment]
I think I have a solution. Let me know if this works for you.

First, I have tagged the current master with 1.0.0 so there is a real release and these new changes don't mess that up.

Then I have given the main XmlResponse class the ability to accept decorators that will run against the content before it is sent. I have created an XmlRepeater class as a decorator.

You can create as many XmlRepeater instances as you need and add them to the response. Each of them takes a placeholder, an element name and an array of data. The class will turn the array into XML, wrap it in an element with the given name and insert it into the XmlResponse result in place of the placeholder.

See the examples/repeater.php for a full code but here's the short version:

```
$data = ['files' => '@placeholder@'];
$files = [
    ['name' => 'file1.txt'],
    ['name' => 'file2.txt']
];
$repeater = new XmlRepeater('@placeholder@', 'file', $files);
$xr = new XmlResponse($data);
$xr->addDecorator($repeater);
$xr->send();
```

This code is in the Repeating-elements branch.

**Comment by twang4turner** [comment]
We tried to use XmlResponse for creating XML. Since We have switched to use DOMDocument instead, we may not have time to try your code, but your solution looks good to me.

Thanks!

**Comment by michalcarson** [comment]
No problem. It was an interesting "code kata" for me.
